export const SEARCH_BY_AUTHOR = 'SEARCH_BY_AUTHOR';

export const SEARCH_ASYNC_BY_AUTHOR = 'SEARCH_ASYNC_BY_AUTHOR';

export const CLOSE_MODAL = 'CLOSE_MODAL';

export const OPEN_MODAL = 'OPEN_MODAL';

export const IS_LOADING = 'IS_LOADING';